#!/usr/bin/env bash
set -euo pipefail

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

info()  { printf "${CYAN}[info]${NC}  %s\n" "$*"; }
ok()    { printf "${GREEN}[ok]${NC}    %s\n" "$*"; }
warn()  { printf "${YELLOW}[warn]${NC}  %s\n" "$*"; }
err()   { printf "${RED}[error]${NC} %s\n" "$*" >&2; }

# ── Prerequisites ──
check_prereqs() {
    local missing=0
    if ! command -v docker &>/dev/null; then
        err "docker is required but not installed."
        missing=1
    fi
    if ! command -v wget &>/dev/null && ! command -v curl &>/dev/null; then
        err "wget or curl is required but neither is installed."
        missing=1
    fi
    if [ "$missing" -ne 0 ]; then
        exit 1
    fi
    ok "Prerequisites satisfied (docker, wget/curl)"
}

# ── Download helper ──
download() {
    local url="$1" dest="$2"
    if command -v wget &>/dev/null; then
        wget -q -O "$dest" "$url"
    else
        curl -fsSL -o "$dest" "$url"
    fi
}

# ── Prompt helpers ──
ask() {
    local prompt="$1" default="${2:-}" reply
    if [ -n "$default" ]; then
        printf "${BOLD}%s${NC} [%s]: " "$prompt" "$default" >/dev/tty
    else
        printf "${BOLD}%s${NC}: " "$prompt" >/dev/tty
    fi
    read -r reply </dev/tty
    echo "${reply:-$default}"
}

ask_password() {
    local prompt="$1" reply
    printf "${BOLD}%s${NC}: " "$prompt" >/dev/tty
    read -rs reply </dev/tty
    echo >/dev/tty
    echo "$reply"
}

ask_number() {
    local prompt="$1" default="${2:-1}" reply
    while true; do
        printf "${BOLD}%s${NC} [%s]: " "$prompt" "$default" >/dev/tty
        read -r reply </dev/tty
        reply="${reply:-$default}"
        if [[ "$reply" =~ ^[0-9]+$ ]] && [ "$reply" -gt 0 ]; then
            echo "$reply"
            return
        fi
        warn "Please enter a positive integer."
    done
}

# ══════════════════════════════════════════════════════════════════════
printf "\n${BOLD}${CYAN}mailagent setup${NC}\n"
printf "Bootstrap docker-mailserver + mailagent on your VPS.\n"
printf "Docs: https://github.com/vrag99/mailagent\n\n"

check_prereqs

# ── 1. Download DMS files ──
info "Downloading docker-mailserver files..."

DMS_BASE="https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master"
download "$DMS_BASE/compose.yaml" compose.yaml
download "$DMS_BASE/mailserver.env" mailserver.env

ok "Downloaded compose.yaml and mailserver.env"

# ── 2. Set SSL_TYPE=letsencrypt ──
sed -i.bak 's/^SSL_TYPE=.*/SSL_TYPE=letsencrypt/' mailserver.env
sed -i.bak 's/^#\s*SSL_TYPE=.*/SSL_TYPE=letsencrypt/' mailserver.env
rm -f mailserver.env.bak
ok "Set SSL_TYPE=letsencrypt in mailserver.env"

# ── 3. Mail hostname ──
MAIL_HOSTNAME=$(ask "Mail hostname (e.g. mail.example.com)" "mail.example.com")
sed -i.bak "s/hostname: mail.example.com/hostname: ${MAIL_HOSTNAME}/" compose.yaml
rm -f compose.yaml.bak
ok "Set hostname to $MAIL_HOSTNAME"

# ── 4. Inboxes ──
NUM_INBOXES=$(ask_number "Number of inboxes to configure" "1")

declare -a INBOX_NAMES=()
declare -a INBOX_ADDRS=()
declare -a INBOX_PASSWORDS=()
ENV_LINES=("# Generated by mailagent setup")

for ((i = 1; i <= NUM_INBOXES; i++)); do
    suffix=""
    [ "$NUM_INBOXES" -gt 1 ] && suffix=" (inbox $i)"

    addr=$(ask "Email address${suffix}")
    display_name=$(ask "Display name${suffix}" "")
    password=$(ask_password "Mailbox password${suffix}")

    INBOX_ADDRS+=("$addr")
    INBOX_NAMES+=("$display_name")
    INBOX_PASSWORDS+=("$password")

    env_var="MAIL_PASSWORD_${i}"
    ENV_LINES+=("${env_var}=${password}")
done

# ── 5. Write mailagent.env (passwords first, AI keys appended later) ──
printf "%s\n" "${ENV_LINES[@]}" > mailagent.env
ok "Wrote mailagent.env with mailbox passwords"

# ── 6. Create inboxes in DMS ──
info "Creating mailboxes in docker-mailserver..."
for ((i = 0; i < NUM_INBOXES; i++)); do
    docker compose run --rm mailserver setup email add "${INBOX_ADDRS[$i]}" "${INBOX_PASSWORDS[$i]}"
    ok "Created mailbox ${INBOX_ADDRS[$i]}"
done

# ── 7. TLS certs ──
echo
info "TLS certificates via certbot"
printf "  Make sure port 80 is open and DNS A record for %s points to this server.\n" "$MAIL_HOSTNAME"
SETUP_TLS=$(ask "Run certbot now? (y/n)" "y")

if [[ "$SETUP_TLS" =~ ^[Yy] ]]; then
    CERT_EMAIL=$(ask "Email for certbot notifications" "${INBOX_ADDRS[0]}")
    docker run --rm -it \
        -v "${PWD}/docker-data/certbot/certs/:/etc/letsencrypt/" \
        -v "${PWD}/docker-data/certbot/logs/:/var/log/letsencrypt/" \
        -p 80:80 \
        certbot/certbot certonly --standalone -d "$MAIL_HOSTNAME" --email "$CERT_EMAIL" --agree-tos --non-interactive
    ok "Certificates obtained for $MAIL_HOSTNAME"
else
    warn "Skipping TLS setup. You will need to configure certificates manually. See https://docker-mailserver.github.io/docker-mailserver/latest/config/security/ssl/ for more details."
fi

# ── 8. Update compose.yaml for certbot volumes + service ──
# Replace the letsencrypt volume mount to use local certbot path
sed -i.bak 's|/etc/letsencrypt/:/etc/letsencrypt/|./docker-data/certbot/certs/:/etc/letsencrypt/|' compose.yaml
rm -f compose.yaml.bak

# Append certbot renewal service
cat >> compose.yaml <<'CERTBOT_BLOCK'

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker-data/certbot/certs/:/etc/letsencrypt/
      - ./docker-data/certbot/logs/:/var/log/letsencrypt/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"
    restart: unless-stopped
CERTBOT_BLOCK

ok "Updated compose.yaml with certbot volume + renewal service"

# ── 9. Relay setup ──
echo
printf "${BOLD}${CYAN}Outbound relay configuration${NC}\n"
cat <<'RELAY_INFO'

Most VPS providers block port 25 (and sometimes 465), which means your
mail server cannot deliver outbound email directly. You need an outbound
SMTP relay service (e.g. Mailgun, SendGrid, Amazon SES, Brevo).

To configure relay, edit mailserver.env and set:

  DEFAULT_RELAY_HOST=[smtp.mailgun.org]:587
  RELAY_USER=postmaster@mg.yourdomain.com
  RELAY_PASSWORD=your-relay-password

Example with Mailgun:
  1. Sign up at mailgun.com, add & verify your domain
  2. Go to Sending > Domain settings > SMTP credentials
  3. Copy the SMTP hostname, username, and password into the vars above

RELAY_INFO
read -rp "Press Enter when configured, or to skip for now..."

# ── 10. AI provider setup ──
echo
printf "${BOLD}${CYAN}AI Provider Setup${NC}\n\n"
printf "Select AI providers (space-separated numbers):\n"
printf "  1) groq       (default model: llama-3.3-70b-versatile)\n"
printf "  2) openai     (default model: gpt-4o)\n"
printf "  3) anthropic  (default model: claude-sonnet-4-20250514)\n"
printf "  4) gemini     (default model: gemini-2.5-flash)\n"
printf "  5) openrouter (default model: google/gemini-2.5-flash)\n\n"

PROVIDER_NAMES=("groq" "openai" "anthropic" "gemini" "openrouter")
PROVIDER_ENV_KEYS=("GROQ_API_KEY" "OPENAI_API_KEY" "ANTHROPIC_API_KEY" "GEMINI_API_KEY" "OPENROUTER_API_KEY")

SELECTED_INPUT=$(ask "Provider numbers (e.g. 1 3)" "1")
read -ra SELECTED_NUMS <<< "$SELECTED_INPUT"

declare -a SELECTED_PROVIDERS=()
for num in "${SELECTED_NUMS[@]}"; do
    idx=$((num - 1))
    if [ "$idx" -ge 0 ] && [ "$idx" -lt 5 ]; then
        SELECTED_PROVIDERS+=("$idx")
    else
        warn "Ignoring invalid selection: $num"
    fi
done

if [ ${#SELECTED_PROVIDERS[@]} -eq 0 ]; then
    err "At least one provider is required."
    exit 1
fi

# Collect API keys
for idx in "${SELECTED_PROVIDERS[@]}"; do
    name="${PROVIDER_NAMES[$idx]}"
    env_key="${PROVIDER_ENV_KEYS[$idx]}"
    api_key=$(ask_password "${name} API key")
    echo "${env_key}=${api_key}" >> mailagent.env
done

ok "API keys written to mailagent.env"

# ── 11. Download mailagent.yml starter config ──
info "Downloading mailagent.yml starter config..."
download "https://raw.githubusercontent.com/vrag99/mailagent/main/examples/mailagent.starter.yml" mailagent.yml
ok "Downloaded mailagent.yml — edit this file to configure providers, inboxes, and workflows"

# ── 12. Append mailagent service to compose.yaml ──
cat >> compose.yaml <<MAILAGENT_BLOCK

  mailagent:
    image: ghcr.io/vrag99/mailagent:latest
    container_name: mailagent
    env_file: mailagent.env
    volumes:
      - ./mailagent.yml:/app/config.yml:ro
      - ./docker-data/dms/mail-data/:/var/mail
    depends_on:
      - mailserver
    restart: unless-stopped

MAILAGENT_BLOCK

ok "Appended mailagent service to compose.yaml"

# ── 13. Final instructions ──
echo
printf "${BOLD}${GREEN}Setup complete!${NC}\n\n"
cat <<FINAL
Next steps:

  1. Edit mailagent.yml to configure your setup:
     - Update providers with the API keys you chose
     - Set your inbox addresses, display names, and passwords
     - Add workflows for each inbox (examples are included as comments)
     See: https://github.com/vrag99/mailagent/tree/main/examples

  2. If you haven't configured outbound relay, edit mailserver.env now.

  3. Start the stack:
     docker compose up -d

  4. Watch mailagent logs:
     docker compose logs -f mailagent

  5. Check docker-mailserver logs:
     docker compose logs -f mailserver

FINAL
