"""Interactive setup wizard for mailagent."""

from __future__ import annotations

import os
from pathlib import Path

import questionary
from rich.console import Console
from rich.panel import Panel

DEFAULT_MODELS = {
    "groq": "llama-3.3-70b-versatile",
    "openai": "gpt-4o",
    "anthropic": "claude-sonnet-4-20250514",
    "gemini": "gemini-2.5-flash",
    "openrouter": "google/gemini-2.5-flash",
}

PROVIDER_TYPES = {
    "groq": "groq",
    "openai": "openai",
    "anthropic": "anthropic",
    "gemini": "gemini",
    "openrouter": "openrouter",
}

PROVIDER_ENV_PREFIX = {
    "groq": "GROQ_API_KEY",
    "openai": "OPENAI_API_KEY",
    "anthropic": "ANTHROPIC_API_KEY",
    "gemini": "GEMINI_API_KEY",
    "openrouter": "OPENROUTER_API_KEY",
}


def run_setup(output_dir: str = ".") -> int:
    console = Console()
    out = Path(output_dir)

    console.print()
    console.print(
        Panel(
            "[bold]mailagent setup wizard[/bold]\n"
            "This will generate a config file and env file to get you started.",
            title="Welcome",
            style="cyan",
        )
    )
    console.print()

    # Mail host
    mail_host = questionary.text(
        "Mail server hostname:",
        default="mail.example.com",
    ).ask()
    if mail_host is None:
        return 1

    # Number of inboxes
    num_inboxes_str = questionary.text(
        "Number of inboxes to configure:",
        default="1",
        validate=lambda v: v.isdigit() and int(v) > 0 or "Must be a positive integer",
    ).ask()
    if num_inboxes_str is None:
        return 1
    num_inboxes = int(num_inboxes_str)

    # Collect inbox info
    inboxes = []
    env_lines = ["# Generated by mailagent setup"]
    for i in range(num_inboxes):
        suffix = f" (inbox {i + 1})" if num_inboxes > 1 else ""
        addr = questionary.text(f"Email address{suffix}:").ask()
        if addr is None:
            return 1
        display_name = questionary.text(f"Display name{suffix}:", default="").ask()
        if display_name is None:
            return 1
        password = questionary.password(f"Mailbox password{suffix}:").ask()
        if password is None:
            return 1

        env_var = f"MAIL_PASSWORD_{i + 1}" if num_inboxes > 1 else "MAIL_PASSWORD"
        env_lines.append(f"{env_var}={password}")
        inboxes.append({
            "address": addr,
            "name": display_name,
            "password_env": env_var,
        })

    # AI providers
    providers = questionary.checkbox(
        "Select AI providers:",
        choices=["groq", "openai", "anthropic", "gemini", "openrouter"],
    ).ask()
    if not providers:
        console.print("[red]At least one provider is required.[/]")
        return 1

    # Per-provider config
    provider_configs = {}
    for prov in providers:
        api_key = questionary.password(f"{prov} API key:").ask()
        if api_key is None:
            return 1
        model = questionary.text(
            f"{prov} model:", default=DEFAULT_MODELS.get(prov, "")
        ).ask()
        if model is None:
            return 1

        env_key = PROVIDER_ENV_PREFIX[prov]
        env_lines.append(f"{env_key}={api_key}")
        provider_configs[prov] = {
            "type": PROVIDER_TYPES[prov],
            "model": model,
            "env_key": env_key,
        }

    # Default providers
    if len(providers) == 1:
        classify_provider = reply_provider = providers[0]
    else:
        classify_provider = questionary.select(
            "Default classify provider:", choices=providers
        ).ask()
        if classify_provider is None:
            return 1
        reply_provider = questionary.select(
            "Default reply provider:", choices=providers
        ).ask()
        if reply_provider is None:
            return 1

    # Generate YAML config
    yaml_lines = [
        "# yaml-language-server: $schema=https://raw.githubusercontent.com/vrag99/mailagent/main/schema.json",
        "providers:",
    ]
    for name, cfg in provider_configs.items():
        yaml_lines += [
            f"  {name}:",
            f"    type: {cfg['type']}",
            f"    model: {cfg['model']}",
            f"    api_key: ${{{cfg['env_key']}}}",
        ]

    yaml_lines += [
        "",
        "defaults:",
        f"  classify_provider: {classify_provider}",
        f"  reply_provider: {reply_provider}",
        "  blocklist:",
        '    from_patterns: ["noreply@", "no-reply@", "mailer-daemon@"]',
        '    headers: ["List-Unsubscribe", "Precedence: bulk"]',
        "",
        "inboxes:",
    ]

    for inbox in inboxes:
        yaml_lines += [
            f"  - address: {inbox['address']}",
        ]
        if inbox["name"]:
            yaml_lines.append(f"    name: {inbox['name']}")
        yaml_lines += [
            "    credentials:",
            f"      password: ${{{inbox['password_env']}}}",
            "    workflows:",
            "      - name: fallback",
            "        match:",
            "          intent: default",
            "        action:",
            "          type: ignore",
        ]

    yaml_lines += [
        "",
        "settings:",
        f"  mail_host: {mail_host}",
    ]

    # Write files
    env_path = out / "mailagent.env"
    yml_path = out / "mailagent.yml"

    env_path.write_text("\n".join(env_lines) + "\n")
    yml_path.write_text("\n".join(yaml_lines) + "\n")

    console.print()
    console.print(f"[green]✓[/] Wrote [bold]{env_path}[/]")
    console.print(f"[green]✓[/] Wrote [bold]{yml_path}[/]")
    console.print()
    console.print(
        Panel(
            "[bold]Next steps:[/bold]\n\n"
            "1. Edit [bold]mailagent.yml[/] to add workflows for your inboxes\n"
            "2. See examples: https://github.com/vrag99/mailagent/tree/main/examples\n"
            "3. Run [bold]mailagent validate -c mailagent.yml[/] to check your config\n"
            "4. Start with [bold]docker compose up -d[/] or [bold]mailagent run -c mailagent.yml[/]",
            title="All done!",
            style="green",
        )
    )

    return 0
