// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BlocklistRequest
 */
export type BlocklistRequest = {
    /**
     * From Patterns
     */
    from_patterns?: Array<string>;
    /**
     * Headers
     */
    headers?: Array<string>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InboxRequest
 */
export type InboxRequest = {
    /**
     * Address
     *
     * Email address for the inbox
     */
    address: string;
    /**
     * Password
     *
     * Mailbox password
     */
    password: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Classify Provider
     */
    classify_provider?: string | null;
    /**
     * Reply Provider
     */
    reply_provider?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    blocklist?: BlocklistRequest | null;
    /**
     * Workflows
     */
    workflows: Array<WorkflowRequest>;
};

/**
 * InboxResponse
 */
export type InboxResponse = {
    /**
     * Address
     */
    address: string;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Classify Provider
     */
    classify_provider: string;
    /**
     * Reply Provider
     */
    reply_provider: string;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Workflows
     */
    workflows?: Array<WorkflowResponse>;
};

/**
 * InboxUpdateRequest
 */
export type InboxUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Classify Provider
     */
    classify_provider?: string | null;
    /**
     * Reply Provider
     */
    reply_provider?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    blocklist?: BlocklistRequest | null;
};

/**
 * KeywordMatchRequest
 */
export type KeywordMatchRequest = {
    /**
     * Any
     */
    any?: Array<string> | null;
    /**
     * All
     */
    all?: Array<string> | null;
};

/**
 * ProviderRequest
 */
export type ProviderRequest = {
    /**
     * Type
     *
     * Provider type: openai, anthropic, gemini, openrouter, groq
     */
    type: string;
    /**
     * Model
     */
    model: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Retries
     */
    retries?: number;
    /**
     * Http Referer
     */
    http_referer?: string | null;
    /**
     * X Title
     */
    x_title?: string | null;
};

/**
 * ProviderResponse
 */
export type ProviderResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Type
     */
    type: string;
    /**
     * Model
     */
    model: string;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Retries
     */
    retries?: number;
};

/**
 * SendEmailRequest
 */
export type SendEmailRequest = {
    /**
     * From Inbox
     *
     * Inbox address to send from
     */
    from_inbox: string;
    /**
     * To
     *
     * Recipient addresses
     */
    to: Array<string>;
    /**
     * Cc
     */
    cc?: Array<string>;
    /**
     * Bcc
     */
    bcc?: Array<string>;
    /**
     * Subject
     */
    subject: string;
    /**
     * Body
     */
    body: string;
    /**
     * Content Type
     */
    content_type?: 'plain' | 'html';
    /**
     * In Reply To
     */
    in_reply_to?: string | null;
    /**
     * References
     */
    references?: string | null;
};

/**
 * SendEmailResponse
 */
export type SendEmailResponse = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Message Id
     */
    message_id?: string | null;
    /**
     * Detail
     */
    detail?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowActionRequest
 */
export type WorkflowActionRequest = {
    /**
     * Type
     *
     * Action type: reply, ignore, notify, webhook
     */
    type: string;
    /**
     * Prompt
     */
    prompt?: string | null;
    /**
     * Webhook
     */
    webhook?: string | null;
    /**
     * Url
     */
    url?: string | null;
    /**
     * Method
     */
    method?: string;
    /**
     * Headers
     */
    headers?: {
        [key: string]: string;
    } | null;
    /**
     * Payload
     */
    payload?: {
        [key: string]: unknown;
    } | null;
    /**
     * Also Reply
     */
    also_reply?: boolean;
    /**
     * Also Webhook
     */
    also_webhook?: boolean;
    /**
     * Webhook Url
     */
    webhook_url?: string | null;
};

/**
 * WorkflowMatchRequest
 */
export type WorkflowMatchRequest = {
    /**
     * Intent
     */
    intent: string;
    keywords?: KeywordMatchRequest | null;
};

/**
 * WorkflowRequest
 */
export type WorkflowRequest = {
    /**
     * Name
     */
    name: string;
    match: WorkflowMatchRequest;
    action: WorkflowActionRequest;
};

/**
 * WorkflowResponse
 */
export type WorkflowResponse = {
    /**
     * Name
     */
    name: string;
    match: WorkflowMatchRequest;
    action: WorkflowActionRequest;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type ListInboxesApiInboxesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/inboxes';
};

export type ListInboxesApiInboxesGetResponses = {
    /**
     * Response List Inboxes Api Inboxes Get
     *
     * Successful Response
     */
    200: Array<InboxResponse>;
};

export type ListInboxesApiInboxesGetResponse = ListInboxesApiInboxesGetResponses[keyof ListInboxesApiInboxesGetResponses];

export type CreateInboxApiInboxesPostData = {
    body: InboxRequest;
    path?: never;
    query?: never;
    url: '/api/inboxes';
};

export type CreateInboxApiInboxesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateInboxApiInboxesPostError = CreateInboxApiInboxesPostErrors[keyof CreateInboxApiInboxesPostErrors];

export type CreateInboxApiInboxesPostResponses = {
    /**
     * Successful Response
     */
    201: InboxResponse;
};

export type CreateInboxApiInboxesPostResponse = CreateInboxApiInboxesPostResponses[keyof CreateInboxApiInboxesPostResponses];

export type DeleteInboxApiInboxesAddressDeleteData = {
    body?: never;
    path: {
        /**
         * Address
         */
        address: string;
    };
    query?: never;
    url: '/api/inboxes/{address}';
};

export type DeleteInboxApiInboxesAddressDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteInboxApiInboxesAddressDeleteError = DeleteInboxApiInboxesAddressDeleteErrors[keyof DeleteInboxApiInboxesAddressDeleteErrors];

export type DeleteInboxApiInboxesAddressDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteInboxApiInboxesAddressDeleteResponse = DeleteInboxApiInboxesAddressDeleteResponses[keyof DeleteInboxApiInboxesAddressDeleteResponses];

export type GetInboxApiInboxesAddressGetData = {
    body?: never;
    path: {
        /**
         * Address
         */
        address: string;
    };
    query?: never;
    url: '/api/inboxes/{address}';
};

export type GetInboxApiInboxesAddressGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInboxApiInboxesAddressGetError = GetInboxApiInboxesAddressGetErrors[keyof GetInboxApiInboxesAddressGetErrors];

export type GetInboxApiInboxesAddressGetResponses = {
    /**
     * Successful Response
     */
    200: InboxResponse;
};

export type GetInboxApiInboxesAddressGetResponse = GetInboxApiInboxesAddressGetResponses[keyof GetInboxApiInboxesAddressGetResponses];

export type UpdateInboxApiInboxesAddressPatchData = {
    body: InboxUpdateRequest;
    path: {
        /**
         * Address
         */
        address: string;
    };
    query?: never;
    url: '/api/inboxes/{address}';
};

export type UpdateInboxApiInboxesAddressPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateInboxApiInboxesAddressPatchError = UpdateInboxApiInboxesAddressPatchErrors[keyof UpdateInboxApiInboxesAddressPatchErrors];

export type UpdateInboxApiInboxesAddressPatchResponses = {
    /**
     * Successful Response
     */
    200: InboxResponse;
};

export type UpdateInboxApiInboxesAddressPatchResponse = UpdateInboxApiInboxesAddressPatchResponses[keyof UpdateInboxApiInboxesAddressPatchResponses];

export type ListWorkflowsApiInboxesInboxAddressWorkflowsGetData = {
    body?: never;
    path: {
        /**
         * Inbox Address
         */
        inbox_address: string;
    };
    query?: never;
    url: '/api/inboxes/{inbox_address}/workflows';
};

export type ListWorkflowsApiInboxesInboxAddressWorkflowsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkflowsApiInboxesInboxAddressWorkflowsGetError = ListWorkflowsApiInboxesInboxAddressWorkflowsGetErrors[keyof ListWorkflowsApiInboxesInboxAddressWorkflowsGetErrors];

export type ListWorkflowsApiInboxesInboxAddressWorkflowsGetResponses = {
    /**
     * Response List Workflows Api Inboxes  Inbox Address  Workflows Get
     *
     * Successful Response
     */
    200: Array<WorkflowResponse>;
};

export type ListWorkflowsApiInboxesInboxAddressWorkflowsGetResponse = ListWorkflowsApiInboxesInboxAddressWorkflowsGetResponses[keyof ListWorkflowsApiInboxesInboxAddressWorkflowsGetResponses];

export type CreateWorkflowApiInboxesInboxAddressWorkflowsPostData = {
    body: WorkflowRequest;
    path: {
        /**
         * Inbox Address
         */
        inbox_address: string;
    };
    query?: never;
    url: '/api/inboxes/{inbox_address}/workflows';
};

export type CreateWorkflowApiInboxesInboxAddressWorkflowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowApiInboxesInboxAddressWorkflowsPostError = CreateWorkflowApiInboxesInboxAddressWorkflowsPostErrors[keyof CreateWorkflowApiInboxesInboxAddressWorkflowsPostErrors];

export type CreateWorkflowApiInboxesInboxAddressWorkflowsPostResponses = {
    /**
     * Successful Response
     */
    201: WorkflowResponse;
};

export type CreateWorkflowApiInboxesInboxAddressWorkflowsPostResponse = CreateWorkflowApiInboxesInboxAddressWorkflowsPostResponses[keyof CreateWorkflowApiInboxesInboxAddressWorkflowsPostResponses];

export type DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteData = {
    body?: never;
    path: {
        /**
         * Inbox Address
         */
        inbox_address: string;
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/inboxes/{inbox_address}/workflows/{name}';
};

export type DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteError = DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteErrors[keyof DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteErrors];

export type DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteResponse = DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteResponses[keyof DeleteWorkflowApiInboxesInboxAddressWorkflowsNameDeleteResponses];

export type GetWorkflowApiInboxesInboxAddressWorkflowsNameGetData = {
    body?: never;
    path: {
        /**
         * Inbox Address
         */
        inbox_address: string;
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/inboxes/{inbox_address}/workflows/{name}';
};

export type GetWorkflowApiInboxesInboxAddressWorkflowsNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowApiInboxesInboxAddressWorkflowsNameGetError = GetWorkflowApiInboxesInboxAddressWorkflowsNameGetErrors[keyof GetWorkflowApiInboxesInboxAddressWorkflowsNameGetErrors];

export type GetWorkflowApiInboxesInboxAddressWorkflowsNameGetResponses = {
    /**
     * Successful Response
     */
    200: WorkflowResponse;
};

export type GetWorkflowApiInboxesInboxAddressWorkflowsNameGetResponse = GetWorkflowApiInboxesInboxAddressWorkflowsNameGetResponses[keyof GetWorkflowApiInboxesInboxAddressWorkflowsNameGetResponses];

export type ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutData = {
    body: WorkflowRequest;
    path: {
        /**
         * Inbox Address
         */
        inbox_address: string;
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/inboxes/{inbox_address}/workflows/{name}';
};

export type ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutError = ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutErrors[keyof ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutErrors];

export type ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutResponses = {
    /**
     * Successful Response
     */
    200: WorkflowResponse;
};

export type ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutResponse = ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutResponses[keyof ReplaceWorkflowApiInboxesInboxAddressWorkflowsNamePutResponses];

export type ListProvidersApiProvidersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/providers';
};

export type ListProvidersApiProvidersGetResponses = {
    /**
     * Response List Providers Api Providers Get
     *
     * Successful Response
     */
    200: Array<ProviderResponse>;
};

export type ListProvidersApiProvidersGetResponse = ListProvidersApiProvidersGetResponses[keyof ListProvidersApiProvidersGetResponses];

export type DeleteProviderApiProvidersNameDeleteData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/providers/{name}';
};

export type DeleteProviderApiProvidersNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProviderApiProvidersNameDeleteError = DeleteProviderApiProvidersNameDeleteErrors[keyof DeleteProviderApiProvidersNameDeleteErrors];

export type DeleteProviderApiProvidersNameDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProviderApiProvidersNameDeleteResponse = DeleteProviderApiProvidersNameDeleteResponses[keyof DeleteProviderApiProvidersNameDeleteResponses];

export type GetProviderApiProvidersNameGetData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/providers/{name}';
};

export type GetProviderApiProvidersNameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProviderApiProvidersNameGetError = GetProviderApiProvidersNameGetErrors[keyof GetProviderApiProvidersNameGetErrors];

export type GetProviderApiProvidersNameGetResponses = {
    /**
     * Successful Response
     */
    200: ProviderResponse;
};

export type GetProviderApiProvidersNameGetResponse = GetProviderApiProvidersNameGetResponses[keyof GetProviderApiProvidersNameGetResponses];

export type CreateProviderApiProvidersNamePostData = {
    body: ProviderRequest;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/providers/{name}';
};

export type CreateProviderApiProvidersNamePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProviderApiProvidersNamePostError = CreateProviderApiProvidersNamePostErrors[keyof CreateProviderApiProvidersNamePostErrors];

export type CreateProviderApiProvidersNamePostResponses = {
    /**
     * Successful Response
     */
    201: ProviderResponse;
};

export type CreateProviderApiProvidersNamePostResponse = CreateProviderApiProvidersNamePostResponses[keyof CreateProviderApiProvidersNamePostResponses];

export type UpdateProviderApiProvidersNamePutData = {
    body: ProviderRequest;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/providers/{name}';
};

export type UpdateProviderApiProvidersNamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProviderApiProvidersNamePutError = UpdateProviderApiProvidersNamePutErrors[keyof UpdateProviderApiProvidersNamePutErrors];

export type UpdateProviderApiProvidersNamePutResponses = {
    /**
     * Successful Response
     */
    200: ProviderResponse;
};

export type UpdateProviderApiProvidersNamePutResponse = UpdateProviderApiProvidersNamePutResponses[keyof UpdateProviderApiProvidersNamePutResponses];

export type SendApiEmailsSendPostData = {
    body: SendEmailRequest;
    path?: never;
    query?: never;
    url: '/api/emails/send';
};

export type SendApiEmailsSendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendApiEmailsSendPostError = SendApiEmailsSendPostErrors[keyof SendApiEmailsSendPostErrors];

export type SendApiEmailsSendPostResponses = {
    /**
     * Successful Response
     */
    200: SendEmailResponse;
};

export type SendApiEmailsSendPostResponse = SendApiEmailsSendPostResponses[keyof SendApiEmailsSendPostResponses];
